### ISSUE TITLE
loggie在golang 1.18 json库解析panic

### ISSUE THREAD

**Issue by LeiZhang-Hunter** [loggie-io/loggie#177]
操作系统:

```
ubuntu 20.04
```

go版本:

```
1.18
```

panic现场：
```
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x477a5f]

goroutine 49 [running]:
runtime.throw({0x2042115?, 0x0?})
        /usr/local/go/src/runtime/panic.go:992 +0x71 fp=0xc00068b748 sp=0xc00068b718 pc=0x447851
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:825 +0x305 fp=0xc00068b798 sp=0xc00068b748 pc=0x45daa5
aeshashbody()
        /usr/local/go/src/runtime/asm_amd64.s:1343 +0x39f fp=0xc00068b7a0 sp=0xc00068b798 pc=0x477a5f
runtime.mapiternext(0xc0004be6c0)
        /usr/local/go/src/runtime/map.go:934 +0x2cb fp=0xc00068b810 sp=0xc00068b7a0 pc=0x4216ab
runtime.mapiterinit(0xc000079400?, 0xc0005aa000?, 0x0?)
        /usr/local/go/src/runtime/map.go:861 +0x228 fp=0xc00068b830 sp=0xc00068b810 pc=0x421388
reflect.mapiterinit(0x420c9d?, 0x1d0f040?, 0xc0005aa008?)
        /usr/local/go/src/runtime/map.go:1373 +0x19 fp=0xc00068b858 sp=0xc00068b830 pc=0x4741f9
github.com/modern-go/reflect2.(*UnsafeMapType).UnsafeIterate(...)
        /home/zhanglei/data/loggie-main/vendor/github.com/modern-go/reflect2/unsafe_map.go:112
github.com/json-iterator/go.(*sortKeysMapEncoder).Encode(0xc0007fe240, 0xc000788e40, 0xc0005ee4e0)
        /home/zhanglei/data/loggie-main/vendor/github.com/json-iterator/go/reflect_map.go:291 +0x225 fp=0xc00068b9c8 sp=0xc00068b858 pc=0x8e19e5
github.com/json-iterator/go.(*onePtrEncoder).Encode(0xc0007fc190, 0xc0005ac660, 0xc0004be6c0?)
        /home/zhanglei/data/loggie-main/vendor/github.com/json-iterator/go/reflect.go:219 +0x82 fp=0xc00068ba00 sp=0xc00068b9c8 pc=0x8d9c02
github.com/json-iterator/go.(*Stream).WriteVal(0xc0005ee4e0, {0x1d405a0, 0xc0005ac660})
        /home/zhanglei/data/loggie-main/vendor/github.com/json-iterator/go/reflect.go:98 +0x158 fp=0xc00068ba70 sp=0xc00068ba00 pc=0x8d8f18
github.com/json-iterator/go.(*frozenConfig).Marshal(0xc000388c80, {0x1d405a0, 0xc0005ac660})
        /home/zhanglei/data/loggie-main/vendor/github.com/json-iterator/go/config.go:299 +0xc9 fp=0xc00068bb08 sp=0xc00068ba70 pc=0x8d0049
github.com/loggie-io/loggie/pkg/sink/codec/json.(*Json).Encode(0xc000114608, {0x23b6b68, 0xc000587320})
        /home/zhanglei/data/loggie-main/pkg/sink/codec/json/json.go:80 +0x152 fp=0xc00068bb60 sp=0xc00068bb08 pc=0x1472ed2
github.com/loggie-io/loggie/pkg/sink/dev.(*Sink).Consume(0xc0005878c0, {0x23a8948?, 0xc0004be680?})
        /home/zhanglei/data/loggie-main/pkg/sink/dev/sink.go:93 +0xbd fp=0xc00068bbd8 sp=0xc00068bb60 pc=0x147363d
github.com/loggie-io/loggie/pkg/core/sink.(*SubscribeInvoker).Invoke(0x43?, {{0x23a8948?, 0xc0004be680?}, {0x7faec044c0b8?, 0xc0005878c0?}})
        /home/zhanglei/data/loggie-main/pkg/core/sink/invoke.go:42 +0x31 fp=0xc00068bc00 sp=0xc00068bbd8 pc=0x635631
github.com/loggie-io/loggie/pkg/interceptor/metric.(*Interceptor).Intercept(0x7faec0de4580?, {0x23996c0?, 0x33fc378?}, {{0x23a8948?, 0xc0004be680?}, {0x7faec044c0b8?, 0xc0005878c0?}})
        /home/zhanglei/data/loggie-main/pkg/interceptor/metric/interceptor.go:76 +0x63 fp=0xc00068bc60 sp=0xc00068bc00 pc=0x1398ea3
github.com/loggie-io/loggie/pkg/pipeline.buildSinkInvokerChain.func1({{0x23a8948?, 0xc0004be680?}, {0x7faec044c0b8?, 0xc0005878c0?}})
        /home/zhanglei/data/loggie-main/pkg/pipeline/pipeline.go:464 +0x54 fp=0xc00068bca8 sp=0xc00068bc60 pc=0x644514
github.com/loggie-io/loggie/pkg/core/sink.(*AbstractInvoker).Invoke(0x20290c0?, {{0x23a8948?, 0xc0004be680?}, {0x7faec044c0b8?, 0xc0005878c0?}})
        /home/zhanglei/data/loggie-main/pkg/core/sink/invoke.go:35 +0x3d fp=0xc00068bcd8 sp=0xc00068bca8 pc=0x63559d
github.com/loggie-io/loggie/pkg/interceptor/retry.(*Interceptor).Intercept(0xc0001ae150, {0x23996a0, 0xc000114698}, {{0x23a8948?, 0xc0004be680?}, {0x7faec044c0b8?, 0xc0005878c0?}})
        /home/zhanglei/data/loggie-main/pkg/interceptor/retry/interceptor.go:129 +0x15e fp=0xc00068bdd8 sp=0xc00068bcd8 pc=0x1399e9e
github.com/loggie-io/loggie/pkg/pipeline.buildSinkInvokerChain.func1({{0x23a8948?, 0xc0004be680?}, {0x7faec044c0b8?, 0xc0005878c0?}})
        /home/zhanglei/data/loggie-main/pkg/pipeline/pipeline.go:464 +0x54 fp=0xc00068be20 sp=0xc00068bdd8 pc=0x644514
github.com/loggie-io/loggie/pkg/core/sink.(*AbstractInvoker).Invoke(0x0?, {{0x23a8948?, 0xc0004be680?}, {0x7faec044c0b8?, 0xc0005878c0?}})
        /home/zhanglei/data/loggie-main/pkg/core/sink/invoke.go:35 +0x3d fp=0xc00068be50 sp=0xc00068be20 pc=0x63559d
github.com/loggie-io/loggie/pkg/pipeline.(*Pipeline).startSinkConsumer.func1({0x23a8948?, 0xc0004be680?})
        /home/zhanglei/data/loggie-main/pkg/pipeline/pipeline.go:400 +0x3e fp=0xc00068be88 sp=0xc00068be50 pc=0x643a1e
github.com/loggie-io/loggie/pkg/pipeline.(*Pipeline).sinkInvokeLoop(0xc0004527e0, 0x0, {{0x7faec044c0b8, 0xc0005878c0}, {0x7faec044bf48, 0xc0001d2380}, {0xc0004e5980, 0x2, 0x2}}, 0xc0002ad220)
        /home/zhanglei/data/loggie-main/pkg/pipeline/pipeline.go:436 +0x1ea fp=0xc00068bf80 sp=0xc00068be88 pc=0x643c4a
github.com/loggie-io/loggie/pkg/pipeline.(*Pipeline).startSinkConsumer.func3()
        /home/zhanglei/data/loggie-main/pkg/pipeline/pipeline.go:416 +0x4e fp=0xc00068bfe0 sp=0xc00068bf80 pc=0x64392e
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc00068bfe8 sp=0xc00068bfe0 pc=0x47a661
created by github.com/loggie-io/loggie/pkg/pipeline.(*Pipeline).startSinkConsumer
        /home/zhanglei/data/loggie-main/pkg/pipeline/pipeline.go:416 +0x5bd

goroutine 1 [chan receive]:
main.main()
        /home/zhanglei/data/loggie-main/cmd/loggie/main.go:126 +0x99b

goroutine 6 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x0?)
        /home/zhanglei/data/loggie-main/vendor/k8s.io/klog/v2/klog.go:1169 +0x6a
created by k8s.io/klog/v2.init.0
        /home/zhanglei/data/loggie-main/vendor/k8s.io/klog/v2/klog.go:420 +0xf6

goroutine 25 [chan receive]:
github.com/panjf2000/ants/v2.(*Pool).purgePeriodically(0xc0001f8d90)
        /home/zhanglei/data/loggie-main/vendor/github.com/panjf2000/ants/v2/pool.go:69 +0x8b
created by github.com/panjf2000/ants/v2.NewPool
        /home/zhanglei/data/loggie-main/vendor/github.com/panjf2000/ants/v2/pool.go:137 +0x34a

goroutine 9 [syscall]:
os/signal.signal_recv()
        /usr/local/go/src/runtime/sigqueue.go:151 +0x2f
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:23 +0x19
created by os/signal.Notify.func1.1
        /usr/local/go/src/os/signal/signal.go:151 +0x2a

goroutine 32 [chan receive]:
github.com/loggie-io/loggie/pkg/core/signals.SetupSignalHandler.func1()
        /home/zhanglei/data/loggie-main/pkg/core/signals/signal.go:39 +0x2d
created by github.com/loggie-io/loggie/pkg/core/signals.SetupSignalHandler
        /home/zhanglei/data/loggie-main/pkg/core/signals/signal.go:38 +0xbc

goroutine 33 [select]:
github.com/loggie-io/loggie/pkg/eventbus/export/logger.(*logger).run(0xc000300000, {0x1, 0x6fc23ac00, 0x0, 0x0, {{0x0, 0x0}, 0x0, 0x0, 0x0, ...}})
        /home/zhanglei/data/loggie-main/pkg/eventbus/export/logger/logger.go:107 +0x19c
created by github.com/loggie-io/loggie/pkg/eventbus/export/logger.Run
        /home/zhanglei/data/loggie-main/pkg/eventbus/export/logger/logger.go:94 +0xff

goroutine 34 [select]:
github.com/loggie-io/loggie/pkg/eventbus/listener/pipeline.(*Listener).run(0xc00036be00)
        /home/zhanglei/data/loggie-main/pkg/eventbus/listener/pipeline/listener.go:84 +0x114
created by github.com/loggie-io/loggie/pkg/eventbus/listener/pipeline.(*Listener).Start
        /home/zhanglei/data/loggie-main/pkg/eventbus/listener/pipeline/listener.go:65 +0x56

goroutine 35 [select]:
github.com/loggie-io/loggie/pkg/eventbus/listener/filesource.(*Listener).run(0xc0004e48a0)
        /home/zhanglei/data/loggie-main/pkg/eventbus/listener/filesource/listener.go:189 +0x13d
created by github.com/loggie-io/loggie/pkg/eventbus/listener/filesource.(*Listener).Start
        /home/zhanglei/data/loggie-main/pkg/eventbus/listener/filesource/listener.go:85 +0x56

goroutine 36 [select]:
github.com/loggie-io/loggie/pkg/eventbus/listener/filewatcher.(*Listener).run(0xc0004e48e0)
        /home/zhanglei/data/loggie-main/pkg/eventbus/listener/filewatcher/listener.go:198 +0x13a
created by github.com/loggie-io/loggie/pkg/eventbus/listener/filewatcher.(*Listener).Start
        /home/zhanglei/data/loggie-main/pkg/eventbus/listener/filewatcher/listener.go:88 +0x56

goroutine 37 [select]:
github.com/loggie-io/loggie/pkg/eventbus/listener/reload.(*Listener).export(0xc0002a3968)
        /home/zhanglei/data/loggie-main/pkg/eventbus/listener/reload/listener.go:93 +0xf4
created by github.com/loggie-io/loggie/pkg/eventbus/listener/reload.(*Listener).Start
        /home/zhanglei/data/loggie-main/pkg/eventbus/listener/reload/listener.go:69 +0x56

goroutine 38 [select]:
github.com/loggie-io/loggie/pkg/eventbus/listener/sink.(*Listener).run(0xc0004e4920)
        /home/zhanglei/data/loggie-main/pkg/eventbus/listener/sink/listener.go:99 +0x126
created by github.com/loggie-io/loggie/pkg/eventbus/listener/sink.(*Listener).Start
        /home/zhanglei/data/loggie-main/pkg/eventbus/listener/sink/listener.go:76 +0x56

goroutine 39 [select]:
github.com/loggie-io/loggie/pkg/eventbus/listener/queue.(*Listener).run(0xc0004e4940)
        /home/zhanglei/data/loggie-main/pkg/eventbus/listener/queue/listener.go:100 +0x126
created by github.com/loggie-io/loggie/pkg/eventbus/listener/queue.(*Listener).Start
        /home/zhanglei/data/loggie-main/pkg/eventbus/listener/queue/listener.go:77 +0x56

goroutine 40 [select]:
github.com/loggie-io/loggie/pkg/eventbus.(*EventCenter).run(0xc0002e0600)
        /home/zhanglei/data/loggie-main/pkg/eventbus/center.go:144 +0xb9
created by github.com/loggie-io/loggie/pkg/eventbus.StartAndRun
        /home/zhanglei/data/loggie-main/pkg/eventbus/center.go:76 +0x65

goroutine 41 [select]:
github.com/loggie-io/loggie/pkg/interceptor/retry.(*Interceptor).run(0xc0001ae150)
        /home/zhanglei/data/loggie-main/pkg/interceptor/retry/interceptor.go:161 +0x1f2
created by github.com/loggie-io/loggie/pkg/interceptor/retry.(*Interceptor).Start
        /home/zhanglei/data/loggie-main/pkg/interceptor/retry/interceptor.go:111 +0x5a

goroutine 42 [select]:
database/sql.(*DB).connectionOpener(0xc00039d520, {0x23b4470, 0xc0004be8c0})
        /usr/local/go/src/database/sql/sql.go:1226 +0x8d
created by database/sql.OpenDB
        /usr/local/go/src/database/sql/sql.go:794 +0x18d

goroutine 43 [select]:
github.com/loggie-io/loggie/pkg/source/file.(*dbHandler).run(0xc000117a00)
        /home/zhanglei/data/loggie-main/pkg/source/file/persistence.go:190 +0x265
created by github.com/loggie-io/loggie/pkg/source/file.newDbHandler
        /home/zhanglei/data/loggie-main/pkg/source/file/persistence.go:110 +0x20c

goroutine 44 [runnable]:
github.com/loggie-io/loggie/pkg/source/file.(*AckChainHandler).run(0xc0002ad180)
        /home/zhanglei/data/loggie-main/pkg/source/file/ack.go:295 +0x1d2
created by github.com/loggie-io/loggie/pkg/source/file.NewAckChainHandler
        /home/zhanglei/data/loggie-main/pkg/source/file/ack.go:264 +0x1c5

goroutine 45 [syscall]:
syscall.Syscall6(0xe8, 0x8, 0xc000613c14, 0x7, 0xffffffffffffffff, 0x0, 0x0)
        /usr/local/go/src/syscall/asm_linux_amd64.s:43 +0x5
golang.org/x/sys/unix.EpollWait(0x0?, {0xc000613c14?, 0x0?, 0x0?}, 0x0?)
        /home/zhanglei/data/loggie-main/vendor/golang.org/x/sys/unix/zsyscall_linux_amd64.go:77 +0x58
github.com/fsnotify/fsnotify.(*fdPoller).wait(0xc000118c00)
        /home/zhanglei/data/loggie-main/vendor/github.com/fsnotify/fsnotify/inotify_poller.go:86 +0x7d
github.com/fsnotify/fsnotify.(*Watcher).readEvents(0xc0002ad1d0)
        /home/zhanglei/data/loggie-main/vendor/github.com/fsnotify/fsnotify/inotify.go:192 +0x26e
created by github.com/fsnotify/fsnotify.NewWatcher
        /home/zhanglei/data/loggie-main/vendor/github.com/fsnotify/fsnotify/inotify.go:59 +0x1c5

goroutine 46 [select]:
github.com/loggie-io/loggie/pkg/source/file.(*Watcher).run(0xc0003b1200)
        /home/zhanglei/data/loggie-main/pkg/source/file/watch.go:613 +0x20b
created by github.com/loggie-io/loggie/pkg/source/file.newWatcher
        /home/zhanglei/data/loggie-main/pkg/source/file/watch.go:79 +0x28c

goroutine 47 [runnable]:
github.com/loggie-io/loggie/pkg/queue/channel.(*Queue).In(0x33c8940?, {0x23b6b68?, 0xc000297230?})
        /home/zhanglei/data/loggie-main/pkg/queue/channel/queue.go:167 +0x36
github.com/loggie-io/loggie/pkg/core/source.(*PublishInvoker).Invoke(0xc0004eb6b0?, {{0x23b6b68?, 0xc000297230?}, {0x7faec044bf48?, 0xc0001d2380?}})
        /home/zhanglei/data/loggie-main/pkg/core/source/invoke.go:55 +0x31
github.com/loggie-io/loggie/pkg/interceptor/maxbytes.(*Interceptor).Intercept(0xc0001145f0, {0x2399700, 0x33fc378}, {{0x23b6b68?, 0xc000297230?}, {0x7faec044bf48?, 0xc0001d2380?}})
        /home/zhanglei/data/loggie-main/pkg/interceptor/maxbytes/interceptor.go:77 +0x11e
github.com/loggie-io/loggie/pkg/pipeline.buildSourceInvokerChain.func1({{0x23b6b68?, 0xc000297230?}, {0x7faec044bf48?, 0xc0001d2380?}})
        /home/zhanglei/data/loggie-main/pkg/pipeline/pipeline.go:609 +0x54
github.com/loggie-io/loggie/pkg/core/source.(*AbstractInvoker).Invoke(0xc0004e8b48?, {{0x23b6b68?, 0xc000297230?}, {0x7faec044bf48?, 0xc0001d2380?}})
        /home/zhanglei/data/loggie-main/pkg/core/source/invoke.go:38 +0x3d
github.com/loggie-io/loggie/pkg/pipeline.(*Pipeline).startSourceProduct.func1({0x23b6b68, 0xc000297230})
        /home/zhanglei/data/loggie-main/pkg/pipeline/pipeline.go:511 +0xb6
github.com/loggie-io/loggie/pkg/source/file.(*Job).ProductEvent(0xc000690300, 0xe5fff, {0x1c68?, 0xc00004e00a?, 0x33c8940?}, {0xc0005dc398, 0x5b, 0x0?})
        /home/zhanglei/data/loggie-main/pkg/source/file/job.go:327 +0x746
github.com/loggie-io/loggie/pkg/source/file.(*Reader).work(0xc00048e750, 0x0)
        /home/zhanglei/data/loggie-main/pkg/source/file/read.go:183 +0xf3e
created by github.com/loggie-io/loggie/pkg/source/file.(*Reader).Start.func1
        /home/zhanglei/data/loggie-main/pkg/source/file/read.go:100 +0x33

goroutine 48 [select]:
github.com/loggie-io/loggie/pkg/queue/channel.(*Queue).worker(0xc0001d2380)
        /home/zhanglei/data/loggie-main/pkg/queue/channel/queue.go:124 +0x293
created by github.com/loggie-io/loggie/pkg/queue/channel.(*Queue).Start
        /home/zhanglei/data/loggie-main/pkg/queue/channel/queue.go:97 +0xed

goroutine 51 [select]:
github.com/loggie-io/loggie/pkg/pipeline.(*Pipeline).survive(0xc0004527e0)
        /home/zhanglei/data/loggie-main/pkg/pipeline/pipeline.go:645 +0xab
created by github.com/loggie-io/loggie/pkg/pipeline.(*Pipeline).Start
        /home/zhanglei/data/loggie-main/pkg/pipeline/pipeline.go:201 +0x1a5

goroutine 52 [select]:
github.com/loggie-io/loggie/pkg/core/reloader.(*Reloader).Run(0xc000111140, 0xc000058300)
        /home/zhanglei/data/loggie-main/pkg/core/reloader/reload.go:61 +0x115
created by main.main
        /home/zhanglei/data/loggie-main/cmd/loggie/main.go:105 +0x77b

goroutine 53 [IO wait]:
internal/poll.runtime_pollWait(0x7faec0545098, 0x72)
        /usr/local/go/src/runtime/netpoll.go:302 +0x89
internal/poll.(*pollDesc).wait(0xc000117b00?, 0x0?, 0x0)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:83 +0x32
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:88
internal/poll.(*FD).Accept(0xc000117b00)
        /usr/local/go/src/internal/poll/fd_unix.go:614 +0x22c
net.(*netFD).accept(0xc000117b00)
        /usr/local/go/src/net/fd_unix.go:172 +0x35
net.(*TCPListener).accept(0xc0001111b8)
        /usr/local/go/src/net/tcpsock_posix.go:139 +0x28
net.(*TCPListener).Accept(0xc0001111b8)
        /usr/local/go/src/net/tcpsock.go:288 +0x3d
net/http.(*Server).Serve(0xc000390460, {0x23b32f8, 0xc0001111b8})
        /usr/local/go/src/net/http/server.go:3039 +0x385
net/http.(*Server).ListenAndServe(0xc000390460)
        /usr/local/go/src/net/http/server.go:2968 +0x7d
net/http.ListenAndServe(...)
        /usr/local/go/src/net/http/server.go:3222
main.main.func2()
        /home/zhanglei/data/loggie-main/cmd/loggie/main.go:119 +0xf1
created by main.main
        /home/zhanglei/data/loggie-main/cmd/loggie/main.go:118 +0x96c

Proces
```

尝试解决方案
```
//json = jsoniter.ConfigFastest
	json = jsoniter.ConfigCompatibleWithStandardLibrary
```

最后采用官方json库后解决，解决代码位置:

```
sink/codec/json.go
```

**Comment by lyp256** [comment]
```golang
package main

import (
	"fmt"

	jsoniter "github.com/json-iterator/go"
)

func main() {
	var m = map[string]interface{}{
		"body": `{"foo":"bar"}}`,
	}
	out, err := jsoniter.ConfigFastest.Marshal(m)
	if err != nil {
		panic(err)
	}
	fmt.Println(string(out))
}

```

通过 go1.18 测试,以上代码在 github.com/json-iterator/go@v1.1.12 上运行正常，在 github.com/json-iterator/go@v1.1.11 上会触发panic ，现目前 main 分支 已经升级到 github.com/json-iterator/go@v1.1.12 下次发版应该能解决问题
