### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by zanderme** [loggie-io/loggie#276]
## What version of Loggie?
v1.2.0

## Expected Behavior
修复空指针问题

## Actual Behavior
空指针异常
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x813941]

goroutine 293 [running]:
github.com/loggie-io/loggie/pkg/pipeline.(*Pipeline).finalizeBatch(0xc00051e140, {0x258bfe0, 0xc000fada00})
	/pkg/pipeline/pipeline.go:345 +0x161
github.com/loggie-io/loggie/pkg/pipeline.(*Pipeline).consumerOutChanAndDrop(0xc00051e140, 0xc000332b40)
	/pkg/pipeline/pipeline.go:182 +0x145
created by github.com/loggie-io/loggie/pkg/pipeline.(*Pipeline).cleanOutChan
	/pkg/pipeline/pipeline.go:169 +0xc5
```

**Comment by ethfoo** [comment]
麻烦发一下使用配置和复现方式

**Comment by ethfoo** [comment]
理论上不会出现batch为空的场景，这里已经优化，你可以尝试使用最新的自动构建的main分支镜像（https://hub.docker.com/r/loggieio/loggie/）
不过还是麻烦发一下配置和复现方式我们研究一下
