### ISSUE TITLE
v1.4.0 在主机上无法使用，启动就奔溃

### ISSUE THREAD

**Issue by vinsonzou** [loggie-io/loggie#491]
## OS
- Rocky Linux 8.4 x64【异常】
- Rocky Linux 8.5 x64【正常】

## What version of Loggie?
v1.4.0

## Steps to Reproduce the Problem
快速上手示例即可复现 https://loggie-io.github.io/docs/getting-started/quick-start/node/

## error info
```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x0]

runtime stack:
runtime.throw({0x2868464?, 0x7fffa35096a0?})
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:992 +0x71
runtime.sigpanic()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/signal_unix.go:802 +0x389

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x1fe4eb0, 0xc00091f028)
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/cgocall.go:157 +0x5c fp=0xc00091f000 sp=0xc00091efc8 pc=0x4058bc
os/user._Cfunc_mygetpwuid_r(0x3e8, 0xc000827e60, 0x5853cb0, 0x400, 0xc00053a320)
	_cgo_gotypes.go:175 +0x4c fp=0xc00091f028 sp=0xc00091f000 pc=0x6b316c
os/user.lookupUnixUid.func1.1(0x3e8, 0x40b51c0?, 0xc00091f0c0?, 0x40f8c7?)
	/opt/hostedtoolcache/go/1.18.10/x64/src/os/user/cgo_lookup_unix.go:102 +0xa6 fp=0xc00091f088 sp=0xc00091f028 pc=0x6b38e6
os/user.lookupUnixUid.func1()
	/opt/hostedtoolcache/go/1.18.10/x64/src/os/user/cgo_lookup_unix.go:102 +0x29 fp=0xc00091f0b8 sp=0xc00091f088 pc=0x6b3829
os/user.retryWithBuffer(0xc0004473b0, 0xc00091f198)
	/opt/hostedtoolcache/go/1.18.10/x64/src/os/user/cgo_lookup_unix.go:244 +0x39 fp=0xc00091f100 sp=0xc00091f0b8 pc=0x6b3f19
os/user.lookupUnixUid(0x3e8)
	/opt/hostedtoolcache/go/1.18.10/x64/src/os/user/cgo_lookup_unix.go:95 +0x10f fp=0xc00091f1d8 sp=0xc00091f100 pc=0x6b362f
os/user.current()
	/opt/hostedtoolcache/go/1.18.10/x64/src/os/user/cgo_lookup_unix.go:48 +0x47 fp=0xc00091f218 sp=0xc00091f1d8 pc=0x6b34a7
os/user.Current.func1()
	/opt/hostedtoolcache/go/1.18.10/x64/src/os/user/lookup.go:15 +0x17 fp=0xc00091f228 sp=0xc00091f218 pc=0x6b2e17
sync.(*Once).doSlow(0x40f565?, 0x2345140?)
	/opt/hostedtoolcache/go/1.18.10/x64/src/sync/once.go:68 +0xc2 fp=0xc00091f288 sp=0xc00091f228 pc=0x484922
sync.(*Once).Do(...)
	/opt/hostedtoolcache/go/1.18.10/x64/src/sync/once.go:59
os/user.Current()
	/opt/hostedtoolcache/go/1.18.10/x64/src/os/user/lookup.go:15 +0x37 fp=0xc00091f2b8 sp=0xc00091f288 pc=0x6b2eb7
github.com/godbus/dbus.getRuntimeDirectory()
	/home/runner/work/loggie/loggie/vendor/github.com/godbus/dbus/conn_other.go:80 +0x19 fp=0xc00091f300 sp=0xc00091f2b8 pc=0x1e304f9
github.com/godbus/dbus.tryDiscoverDbusSessionBusAddress()
	/home/runner/work/loggie/loggie/vendor/github.com/godbus/dbus/conn_other.go:52 +0x2b fp=0xc00091f3a8 sp=0xc00091f300 pc=0x1e3028b
github.com/godbus/dbus.getSessionBusAddress()
	/home/runner/work/loggie/loggie/vendor/github.com/godbus/dbus/conn.go:83 +0x66 fp=0xc00091f3e8 sp=0xc00091f3a8 pc=0x1e2b726
github.com/godbus/dbus.SessionBusPrivate({0x0, 0x0, 0x0})
	/home/runner/work/loggie/loggie/vendor/github.com/godbus/dbus/conn.go:92 +0x28 fp=0xc00091f420 sp=0xc00091f3e8 pc=0x1e2b7a8
github.com/godbus/dbus.SessionBus()
	/home/runner/work/loggie/loggie/vendor/github.com/godbus/dbus/conn.go:63 +0xce fp=0xc00091f4a0 sp=0xc00091f420 pc=0x1e2b46e
github.com/99designs/keyring.init.1()
	/home/runner/work/loggie/loggie/vendor/github.com/99designs/keyring/kwallet.go:24 +0x45 fp=0xc00091f4d0 sp=0xc00091f4a0 pc=0x1e51dc5
runtime.doInit(0x3f58a40)
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/proc.go:6230 +0x126 fp=0xc00091f600 sp=0xc00091f4d0 pc=0x4499e6
runtime.doInit(0x3f4b420)
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/proc.go:6207 +0x71 fp=0xc00091f730 sp=0xc00091f600 pc=0x449931
runtime.doInit(0x3f48060)
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/proc.go:6207 +0x71 fp=0xc00091f860 sp=0xc00091f730 pc=0x449931
runtime.doInit(0x3f57840)
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/proc.go:6207 +0x71 fp=0xc00091f990 sp=0xc00091f860 pc=0x449931
runtime.doInit(0x3f5eca0)
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/proc.go:6207 +0x71 fp=0xc00091fac0 sp=0xc00091f990 pc=0x449931
runtime.doInit(0x3f5dd80)
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/proc.go:6207 +0x71 fp=0xc00091fbf0 sp=0xc00091fac0 pc=0x449931
runtime.doInit(0x3f53a80)
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/proc.go:6207 +0x71 fp=0xc00091fd20 sp=0xc00091fbf0 pc=0x449931
runtime.doInit(0x3f60620)
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/proc.go:6207 +0x71 fp=0xc00091fe50 sp=0xc00091fd20 pc=0x449931
runtime.doInit(0x3f59860)
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/proc.go:6207 +0x71 fp=0xc00091ff80 sp=0xc00091fe50 pc=0x449931
runtime.main()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/proc.go:233 +0x1d3 fp=0xc00091ffe0 sp=0xc00091ff80 pc=0x43c973
runtime.goexit()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc00091ffe8 sp=0xc00091ffe0 pc=0x46d801

goroutine 19 [sleep]:
time.Sleep(0x6fc23ac00)
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/time.go:194 +0x12e
sigs.k8s.io/controller-runtime/pkg/log.init.0.func1()
	/home/runner/work/loggie/loggie/vendor/sigs.k8s.io/controller-runtime/pkg/log/log.go:63 +0x38
created by sigs.k8s.io/controller-runtime/pkg/log.init.0
	/home/runner/work/loggie/loggie/vendor/sigs.k8s.io/controller-runtime/pkg/log/log.go:62 +0x25

goroutine 20 [chan receive]:
github.com/panjf2000/ants/v2.(*Pool).purgePeriodically(0xc000414000)
	/home/runner/work/loggie/loggie/vendor/github.com/panjf2000/ants/v2/pool.go:69 +0x8b
created by github.com/panjf2000/ants/v2.NewPool
	/home/runner/work/loggie/loggie/vendor/github.com/panjf2000/ants/v2/pool.go:137 +0x34a
```

**Comment by ethfoo** [comment]
看起来是引入CGO导致的（sqlite持久化需要），参考一下：https://loggie-io.github.io/docs/user-guide/troubleshot/problems/#netcgolookupip-segmentation-violation

最新的main分支引入了badger作为新的持久化引擎，可以无需CGO

**Comment by vinsonzou** [comment]
> 看起来是引入CGO导致的（sqlite持久化需要），参考一下：https://loggie-io.github.io/docs/user-guide/troubleshot/problems/#netcgolookupip-segmentation-violation
> 
> 最新的main分支引入了badger作为新的持久化引擎，可以无需CGO

使用此配置还是一样报错。另外发现个新问题，用root用户是没任何问题的，普通用户就会奔溃。

**Comment by vinsonzou** [comment]
最新分支build without sqlite可以正常使用了。
