### ISSUE TITLE
loggie运行一段时间崩溃，提示panic: query registry fail: database is locked

### ISSUE THREAD

**Issue by budong** [loggie-io/loggie#521]
报错信息如下，请问会是什么原因呢，我改如何排查呢

```
2023-04-12 21:15:14 INF data0/budong/loggie/pkg/source/file/watch.go:677 > watcher stop
panic: query registry fail: database is locked

goroutine 118 [running]:
github.com/loggie-io/loggie/pkg/util/persistence/driver.(*Engine).findBySql(0xc000cbe558, {0xc000ffe000, 0xc8})
        /data0/budong/loggie/pkg/util/persistence/driver/sqlite.go:263 +0x5da
github.com/loggie-io/loggie/pkg/util/persistence/driver.(*Engine).FindBy(0x30?, {0xc00061a3d0?, 0xc001000b60?}, {0xc000ba7198, 0x5}, {0xc000ba7168, 0x4})
        /data0/budong/loggie/pkg/util/persistence/driver/sqlite.go:162 +0x11b
github.com/loggie-io/loggie/pkg/util/persistence.(*DbHandler).FindBy(0x7f098ab8e000?, {0xc00061a3d0, 0xd}, {0xc000ba7198, 0x5}, {0xc000ba7168, 0x4})
        /data0/budong/loggie/pkg/util/persistence/persistence.go:189 +0xcd
github.com/loggie-io/loggie/pkg/source/file.(*Watcher).findExistJobRegistry(...)
        /data0/budong/loggie/pkg/source/file/watch.go:143
github.com/loggie-io/loggie/pkg/source/file.(*Watcher).eventBus(0xc000cee0c0, {0xc000a1ac90?, 0xc00033e280?, {0x0?, 0xc0014b0410?}})
        /data0/budong/loggie/pkg/source/file/watch.go:283 +0x1e5
github.com/loggie-io/loggie/pkg/source/file.(*Watcher).createOrRename(0xc000cee0c0, {0xc0045425d0?, 0x1d?}, 0xc0005decf8?, 0x0)
        /data0/budong/loggie/pkg/source/file/watch.go:444 +0x234
github.com/loggie-io/loggie/pkg/source/file.(*Watcher).scanPaths(0xc0004daa48?, {0xc000ba7168, 0x4}, {0xc000ba7198, 0x5}, {0xc000a08ab0?, 0x1, 0xc0005dee20?}, 0x4d6877?, 0x0)
        /data0/budong/loggie/pkg/source/file/watch.go:426 +0x30b
github.com/loggie-io/loggie/pkg/source/file.(*Watcher).scanTaskNewFiles(0x20?, 0x5?)
        /data0/budong/loggie/pkg/source/file/watch.go:370 +0x92
github.com/loggie-io/loggie/pkg/source/file.(*Watcher).scanNewFiles(...)
        /data0/budong/loggie/pkg/source/file/watch.go:357
github.com/loggie-io/loggie/pkg/source/file.(*Watcher).scan(0xc000cee0c0)
        /data0/budong/loggie/pkg/source/file/watch.go:524 +0x9e
github.com/loggie-io/loggie/pkg/source/file.(*Watcher).run(0xc000cee0c0)
        /data0/budong/loggie/pkg/source/file/watch.go:695 +0x2bb
created by github.com/loggie-io/loggie/pkg/source/file.newWatcher
        /data0/budong/loggie/pkg/source/file/watch.go:83 +0x2ac
```

**Comment by ethfoo** [comment]
用的是哪个版本？

**Comment by budong** [comment]
基于最新的代码编译的 commit bb1428c2ffca7842bb041d391e36c1104d8b8ee3

TAG = main-bb1428c2

**Comment by budong** [comment]
@ethfoo 这个问题看着不是偶发，我跑了一天后，就又panic了

# ll data/
total 64
-rw-r--r-- 1 root root 45056 Apr 14 18:00 loggie.db
-rw-r--r-- 1 root root 12824 Apr 14 18:00 loggie.db-journal

系统是Cenos 8的，多了一个loggie.db-journal的文件

**Comment by ethfoo** [comment]
麻烦发一下loggie.yml和pipeline配置看下
